### ISSUE TITLE
panic on Windows in fixDeletedItemsList (invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by kierenj** [rikatz/kubepug#319]
````
GitVersion:    v1.4.0
GitCommit:     4de32d695b27c52c16d4a801b613b78e45e28ca9
GitTreeState:  clean
BuildDate:     2022-08-21T18:25:40
GoVersion:     go1.18.5
Compiler:      gc
Platform:      windows/amd64
````

Commandline: `kubepug`

Result:

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x1df5ad4]

goroutine 1 [running]:
github.com/rikatz/kubepug/pkg/kubepug/input/k8s.fixDeletedItemsList({0x2322800?, 0xc000006870?}, {0xc000006760, 0x1, 0x0?}, {{0x20ff513, 0x14}, {0x20f17d1, 0x9}, {0x20ef752, ...}})
        github.com/rikatz/kubepug/pkg/kubepug/input/k8s/deleted.go:224 +0xf4
github.com/rikatz/kubepug/pkg/kubepug/input/k8s.GetDeleted(0x2e4932c0108?, 0x30?)
        github.com/rikatz/kubepug/pkg/kubepug/input/k8s/deleted.go:170 +0x8fd
github.com/rikatz/kubepug/pkg/kubepug.K8sInput.ListDeleted(...)
        github.com/rikatz/kubepug/pkg/kubepug/k8sinput.go:28
github.com/rikatz/kubepug/pkg/kubepug.GetDeprecations({0x23299a8, 0xc00161b170})
        github.com/rikatz/kubepug/pkg/kubepug/deprecator.go:17 +0x5c
github.com/rikatz/kubepug/lib.(*Kubepug).getResults(0x20ef14d?, 0xc000130000?)
        github.com/rikatz/kubepug/lib/kubepug.go:73 +0xd9
github.com/rikatz/kubepug/lib.(*Kubepug).GetDeprecated(0xc0000c1ce8)
        github.com/rikatz/kubepug/lib/kubepug.go:56 +0x177
github.com/rikatz/kubepug/cmd.runPug(0x2db5cc0?, {0x2e21c10?, 0x0?, 0x0?})
        github.com/rikatz/kubepug/cmd/root.go:74 +0x2e5
github.com/spf13/cobra.(*Command).execute(0x2db5cc0, {0xc0001081f0, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x2db5cc0)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
github.com/rikatz/kubepug/cmd.Execute()
        github.com/rikatz/kubepug/cmd/root.go:141 +0x25
main.main()
        github.com/rikatz/kubepug/main.go:6 +0x17
````

**Comment by andre161292** [comment]
This also happens on Linux, too if i'm targeting a Kubernetes-Version >= 1.22 (coming from 1.17.17). For anything below 1.22.0, it works fine.
When checking 1.24.4 (another cluster i've running) against anything above that, it works too. 
This is a deficiency in some internal rather than a Windows incompatibility. 

Looking at the code, `newApiItems` seems to be nil and it looks like we could fix this by only executing the first loop, if newApiItems is not nil. At least that works for my case. I haven't dug into the logic and code at all.

If others confirm that this is the correct solution, i'll file a PR. Try it out in my branch: https://github.com/andre161292/kubepug/tree/bugfix/319-check-new-items-not-null

**Comment by rikatz** [comment]
I have fixed an error on this logic, take a look on the last commit. 

I plan doing an alpha release today! Thanks for reporting it!

**Comment by rikatz** [comment]
Can you test with https://github.com/rikatz/kubepug/releases/tag/v1.5.0-alpha.0 please?

Thanks!

**Comment by rikatz** [comment]
I'm considering this as fixed, thanks for using the project!
